name: release

on:
  push:
    branches:
      - main
    tags:
      - 'release:*'

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            rid: linux-x64
          # - os: windows-latest
          #   rid: win-x64
          # - os: macos-latest
          #   rid: osx-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish .NET project
        run: |
          dotnet publish src/Bert/Bert.csproj \
            --configuration Release \
            --framework net9.0 \
            --runtime ${{ matrix.rid }} \
            --self-contained true \
            /p:PublishAot=true \
            --output ./publish/${{ matrix.rid }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.rid }}-binaries
          path: ./publish/${{ matrix.rid }}

  create-release:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.rid }}-binaries
          path: ./artifacts/${{ matrix.rid }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ./artifacts/${{ matrix.rid }}/*
          # files: |
          #   ./artifacts/linux-x64/*
          #   ./artifacts/win-x64/*
          #   ./artifacts/osx-x64/*
